### ISSUE TITLE
shallow with globals don't mock router

### ISSUE THREAD

**Issue by nikit-cpp** [eddyerburgh/avoriaz#124]
Hello, I've googled for proper way to mock router and read your [article](https://eddyerburgh.me/stub-$route-in-vue-unit-tests)
but if I define $router via globals -- it hasn't any effect -- I get
```
TypeError: Cannot read property 'push' of undefined
```

Here is [branch](https://github.com/nikit-cpp/blog/tree/avoriaz-mock-router) in my project

**Steps to reproduce**
```
cd frontend
npm run unit -- --browsers=Chrome
```

file https://github.com/nikit-cpp/blog/blob/avoriaz-mock-router/frontend/src/test/frontend/specs/PostView.spec.js#L41

Where I was mistaken ? Is this bug ?

**Comment by eddyerburgh** [comment]
You're probably calling `Vue.use(Router)` before running tests, see this issue -https://github.com/eddyerburgh/avoriaz/issues/80

**Comment by nikit-cpp** [comment]
Thanks, I don't think if I've imported only constants from my router.js, Vue.use() will be invokend

**Comment by eddyerburgh** [comment]
Try not importing them and see if it fixes the issue.

When you `require` a module, it runs the file. So that `Vue.use` will be run. (imports are transpiled to require functions). 

I suggest splitting up your router into separate files, and only calling Vue.use(router) in a main file that instantiates Vue. It's not an ideal solution, but it's the only way you'll be able to mock Router.
