### ISSUE TITLE
shallow does not reach created hook

### ISSUE THREAD

**Issue by disitec** [eddyerburgh/avoriaz#61]
Is this an expected behaviour? In that case? How can I stub child component without loosing the execution of created hook?

Thank you

**Comment by eddyerburgh** [comment]
I added this yesterday. I think it should be expected behavior. There currently isn't a way, but I can add an option to pass to shallow if you have a good use case.

My thoughts were that if you are unit testing a component in isolation, you shouldn't care what a child component does. You can have a separate test for the component with the created event to check it is behaving as expected.

But like I said, I'm happy to add an option in to bypass stubbing child lifecycle events if you find it valuable. What is your use case?

**Comment by disitec** [comment]
Of course, I allways test component in isolation. In my case I want to test only one component but stubbing the child components inside it.

Is in this main component when created is never reached. I need to call some api (mocking it in my case) when created. But it is never mocked.

Why created hook does not exists in this case?

**Comment by eddyerburgh** [comment]
Oh sorry, I misunderstood. So created on the component you're testing is being stubbed? This isn't expected behavior, it's a bug. I'll look into it

**Comment by eddyerburgh** [comment]
Bug should be fixed in 2.1.2 👍

**Comment by disitec** [comment]
Thank you. Awesome work!
